// ============================================================
//  Player Name Translations (English → 中文)
//  2026 World Cup key players
// ============================================================

const NAME_MAP: Record<string, string> = {
  // Argentina
  "Lionel Messi": "梅西",
  "Julián Álvarez": "阿尔瓦雷斯",
  "Julian Alvarez": "阿尔瓦雷斯",
  "Emiliano Martínez": "马丁内斯",
  "Emiliano Martinez": "马丁内斯",
  "Rodrigo De Paul": "德保罗",
  "Ángel Di María": "迪马利亚",
  "Angel Di Maria": "迪马利亚",
  "Alexis Mac Allister": "麦卡利斯特",
  "Enzo Fernández": "恩佐",
  "Enzo Fernandez": "恩佐",
  "Nicolás Otamendi": "奥塔门迪",
  "Nicolas Otamendi": "奥塔门迪",
  "Cristian Romero": "罗梅罗",
  "Lautaro Martínez": "劳塔罗",
  "Lautaro Martinez": "劳塔罗",
  "Leandro Paredes": "帕雷德斯",
  "Nicolás Tagliafico": "塔利亚菲科",
  "Nahuel Molina": "莫利纳",
  "Giovani Lo Celso": "洛塞尔索",
  "Paulo Dybala": "迪巴拉",
  "Gonzalo Montiel": "蒙铁尔",
  "Gerónimo Rulli": "鲁利",
  // Brazil
  "Vinicius Jr.": "维尼修斯",
  "Vinicius Junior": "维尼修斯",
  "Rodrygo": "罗德里戈",
  "Alisson Becker": "阿利松",
  "Alisson": "阿利松",
  "Ederson": "埃德森",
  "Marquinhos": "马尔基尼奥斯",
  "Éder Militão": "米利唐",
  "Eder Militao": "米利唐",
  "Gabriel Magalhães": "加布里埃尔",
  "Gabriel": "加布里埃尔",
  "Raphinha": "拉菲尼亚",
  "Bruno Guimarães": "吉马良斯",
  "Casemiro": "卡塞米罗",
  "Neymar": "内马尔",
  "Endrick": "恩德里克",
  "Savinho": "萨维尼奥",
  // France
  "Kylian Mbappé": "姆巴佩",
  "Kylian Mbappe": "姆巴佩",
  "Aurélien Tchouaméni": "楚阿梅尼",
  "Aurelien Tchouameni": "楚阿梅尼",
  "Antoine Griezmann": "格列兹曼",
  "Ousmane Dembélé": "登贝莱",
  "Ousmane Dembele": "登贝莱",
  "Eduardo Camavinga": "卡马文加",
  "Warren Zaïre-Emery": "扎伊尔埃梅里",
  "Mike Maignan": "迈尼昂",
  "William Saliba": "萨利巴",
  "Ibrahima Konaté": "科纳特",
  "Dayot Upamecano": "于帕梅卡诺",
  "Theo Hernández": "特奥",
  "Theo Hernandez": "特奥",
  "Kingsley Coman": "科曼",
  "Marcus Thuram": "图拉姆",
  "Randal Kolo Muani": "科洛穆阿尼",
  "Olivier Giroud": "吉鲁",
  "N'Golo Kanté": "坎特",
  "Adrien Rabiot": "拉比奥",
  // England
  "Jude Bellingham": "贝林厄姆",
  "Harry Kane": "凯恩",
  "Phil Foden": "福登",
  "Bukayo Saka": "萨卡",
  "Declan Rice": "赖斯",
  "Cole Palmer": "帕尔默",
  "Trent Alexander-Arnold": "阿诺德",
  "John Stones": "斯通斯",
  "Kyle Walker": "沃克",
  "Jordan Pickford": "皮克福德",
  "Jack Grealish": "格拉利什",
  "Marcus Rashford": "拉什福德",
  "James Maddison": "麦迪逊",
  "Conor Gallagher": "加拉格尔",
  // Spain
  "Lamine Yamal": "亚马尔",
  "Pedri": "佩德里",
  "Gavi": "加维",
  "Dani Olmo": "奥尔莫",
  "Nico Williams": "尼科威廉姆斯",
  "Rodri": "罗德里",
  "Unai Simón": "乌奈西蒙",
  "Unai Simon": "乌奈西蒙",
  "Aymeric Laporte": "拉波尔特",
  "Marc Cucurella": "库库雷利亚",
  "Fabián Ruiz": "法比安",
  "Fabian Ruiz": "法比安",
  "Álvaro Morata": "莫拉塔",
  "Alvaro Morata": "莫拉塔",
  "Mikel Oyarzabal": "奥亚萨瓦尔",
  "Ferrán Torres": "费兰托雷斯",
  "Ferran Torres": "费兰托雷斯",
  "Alejandro Balde": "巴尔德",
  "Pau Cubarsí": "库巴西",
  // Portugal
  "Cristiano Ronaldo": "C罗",
  "Bruno Fernandes": "B费",
  "Bernardo Silva": "B席",
  "Rafael Leão": "莱奥",
  "Rafael Leao": "莱奥",
  "Rúben Dias": "鲁本迪亚斯",
  "Ruben Dias": "鲁本迪亚斯",
  "Diogo Costa": "迪奥戈科斯塔",
  "João Cancelo": "坎塞洛",
  "Joao Cancelo": "坎塞洛",
  "Diogo Dalot": "达洛特",
  "Nuno Mendes": "努诺门德斯",
  "João Palhinha": "帕利尼亚",
  "Vitinha": "维蒂尼亚",
  "Gonçalo Ramos": "贡萨洛拉莫斯",
  "Goncalo Ramos": "贡萨洛拉莫斯",
  "Pedro Neto": "佩德罗内托",
  "Diogo Jota": "若塔",
  // Germany
  "Jamal Musiala": "穆西亚拉",
  "Florian Wirtz": "维尔茨",
  "Kai Havertz": "哈弗茨",
  "Leroy Sané": "萨内",
  "Leroy Sane": "萨内",
  "Serge Gnabry": "格纳布里",
  "İlkay Gündoğan": "京多安",
  "Ilkay Gundogan": "京多安",
  "Joshua Kimmich": "基米希",
  "Antonio Rüdiger": "吕迪格",
  "Antonio Rudiger": "吕迪格",
  "Marc-André ter Stegen": "特尔施特根",
  "Manuel Neuer": "诺伊尔",
  "Thomas Müller": "穆勒",
  "Thomas Muller": "穆勒",
  "Niclas Füllkrug": "菲尔克鲁格",
  "Leon Goretzka": "格雷茨卡",
  "Jonathan Tah": "塔赫",
  // Italy
  "Nicolò Barella": "巴雷拉",
  "Nicolo Barella": "巴雷拉",
  "Federico Chiesa": "基耶萨",
  "Gianluigi Donnarumma": "多纳鲁马",
  "Alessandro Bastoni": "巴斯托尼",
  "Federico Dimarco": "迪马尔科",
  "Nicolò Zaniolo": "扎尼奥洛",
  "Sandro Tonali": "托纳利",
  "Davide Frattesi": "弗拉泰西",
  "Giacomo Raspadori": "拉斯帕多里",
  "Mateo Retegui": "雷特吉",
  // Netherlands
  "Virgil van Dijk": "范戴克",
  "Frenkie de Jong": "德容",
  "Matthijs de Ligt": "德里赫特",
  "Cody Gakpo": "加克波",
  "Xavi Simons": "哈维西蒙斯",
  "Memphis Depay": "德佩",
  "Donyell Malen": "马伦",
  "Denzel Dumfries": "邓弗里斯",
  "Nathan Aké": "阿克",
  "Jeremie Frimpong": "弗林蓬",
  "Ryan Gravenberch": "赫拉芬贝赫",
  "Teun Koopmeiners": "库普梅纳斯",
  "Bart Verbruggen": "费布鲁亨",
  // Belgium
  "Kevin De Bruyne": "德布劳内",
  "Romelu Lukaku": "卢卡库",
  "Jérémy Doku": "多库",
  "Jeremy Doku": "多库",
  "Leandro Trossard": "特罗萨德",
  "Amadou Onana": "奥纳纳",
  "Youri Tielemans": "蒂勒曼斯",
  "Loïs Openda": "奥蓬达",
  "Charles De Ketelaere": "德凯特拉雷",
  "Thibaut Courtois": "库尔图瓦",
  // Croatia
  "Luka Modrić": "莫德里奇",
  "Luka Modric": "莫德里奇",
  "Joško Gvardiol": "格瓦迪奥尔",
  "Josko Gvardiol": "格瓦迪奥尔",
  "Mateo Kovačić": "科瓦契奇",
  "Mateo Kovacic": "科瓦契奇",
  "Marcelo Brozović": "布罗佐维奇",
  "Ivan Perišić": "佩里西奇",
  "Andrej Kramarić": "克拉马里奇",
  "Dominik Livaković": "利瓦科维奇",
  // Uruguay
  "Federico Valverde": "巴尔韦德",
  "Darwin Núñez": "努涅斯",
  "Darwin Nunez": "努涅斯",
  "Ronald Araújo": "阿劳霍",
  "Ronald Araujo": "阿劳霍",
  "José Giménez": "希门尼斯",
  "Jose Gimenez": "希门尼斯",
  "Manuel Ugarte": "乌加特",
  "Luis Suárez": "苏亚雷斯",
  "Luis Suarez": "苏亚雷斯",
  "Edinson Cavani": "卡瓦尼",
  "Giorgian de Arrascaeta": "德阿拉斯卡埃塔",
  "Facundo Pellistri": "佩利斯特里",
  // USA
  "Christian Pulisic": "普利西奇",
  "Weston McKennie": "麦肯尼",
  "Timothy Weah": "维阿",
  "Giovanni Reyna": "雷纳",
  "Tyler Adams": "亚当斯",
  "Antonee Robinson": "罗宾逊",
  "Matt Turner": "特纳",
  "Folarin Balogun": "巴洛贡",
  "Yunus Musah": "穆萨",
  "Sergiño Dest": "德斯特",
  // Mexico
  "Santiago Giménez": "希门尼斯",
  "Santiago Gimenez": "希门尼斯",
  "Hirving Lozano": "洛萨诺",
  "Edson Álvarez": "阿尔瓦雷斯",
  "Edson Alvarez": "阿尔瓦雷斯",
  "Guillermo Ochoa": "奥乔亚",
  "Raúl Jiménez": "劳尔希门尼斯",
  "Julián Araujo": "阿劳霍",
  // Canada
  "Alphonso Davies": "戴维斯",
  "Jonathan David": "戴维",
  "Stephen Eustáquio": "欧斯塔基奥",
  "Tajon Buchanan": "布坎南",
  "Cyle Larin": "拉林",
  // Japan
  "Kaoru Mitoma": "三笘薰",
  "Takefusa Kubo": "久保建英",
  "Daichi Kamada": "镰田大地",
  "Wataru Endo": "远藤航",
  "Hidemasa Morita": "守田英正",
  "Ritsu Dōan": "堂安律",
  "Ritsu Doan": "堂安律",
  "Takumi Minamino": "南野拓实",
  "Kyogo Furuhashi": "古桥亨梧",
  "Maya Yoshida": "吉田麻也",
  "Ko Itakura": "板仓滉",
  "Ao Tanaka": "田中碧",
  "Daizen Maeda": "前田大然",
  "Reo Hatate": "旗手怜央",
  // South Korea
  "Son Heung-min": "孙兴慜",
  "Son Heungmin": "孙兴慜",
  "Hwang Hee-chan": "黄喜灿",
  "Kim Min-jae": "金玟哉",
  "Lee Kang-in": "李刚仁",
  "Lee Kangin": "李刚仁",
  "Cho Gue-sung": "曹圭成",
  "Jung Woo-young": "郑优营",
  // Nigeria
  "Victor Osimhen": "奥西姆亨",
  "Ademola Lookman": "卢克曼",
  "Alex Iwobi": "伊沃比",
  "Samuel Chukwueze": "丘库埃泽",
  "Wilfred Ndidi": "恩迪迪",
  "Kelechi Iheanacho": "伊希纳乔",
  "Taiwo Awoniyi": "阿沃尼伊",
  "Frank Onyeka": "奥涅卡",
  // Morocco
  "Achraf Hakimi": "阿什拉夫",
  "Youssef En-Nesyri": "恩内斯里",
  "Hakim Ziyech": "齐耶赫",
  "Noussair Mazraoui": "马兹拉维",
  "Sofyan Amrabat": "阿姆拉巴特",
  "Brahim Díaz": "迪亚斯",
  "Brahim Diaz": "迪亚斯",
  "Yassine Bounou": "布努",
  "Nayef Aguerd": "阿盖尔",
  // Senegal
  "Sadio Mané": "马内",
  "Sadio Mane": "马内",
  "Ismaïla Sarr": "萨尔",
  "Kalidou Koulibaly": "库利巴利",
  "Édouard Mendy": "门迪",
  "Edouard Mendy": "门迪",
  "Nicolas Jackson": "杰克逊",
  "Pape Matar Sarr": "帕普萨尔",
  "Idrissa Gueye": "盖耶",
  // Egypt
  "Mohamed Salah": "萨拉赫",
  "Omar Marmoush": "马尔穆什",
  "Trézéguet": "特雷泽盖",
  "Mostafa Mohamed": "穆斯塔法穆罕默德",
  // Colombia
  "Luis Díaz": "迪亚斯",
  "Luis Diaz": "迪亚斯",
  "James Rodríguez": "J罗",
  "James Rodriguez": "J罗",
  "Jhon Durán": "杜兰",
  "Jefferson Lerma": "莱尔马",
  "Davinson Sánchez": "桑切斯",
  "Daniel Muñoz": "穆尼奥斯",
  "Jhon Arias": "阿里亚斯",
  // Ecuador
  "Moises Caicedo": "凯塞多",
  "Piero Hincapié": "因卡皮耶",
  "Enner Valencia": "瓦伦西亚",
  "Kendry Páez": "派斯",
  // Ghana
  "Mohammed Kudus": "库杜斯",
  "Thomas Partey": "帕尔特伊",
  "Iñaki Williams": "伊尼亚基威廉姆斯",
  "Inaki Williams": "伊尼亚基威廉姆斯",
  "Antoine Semenyo": "塞门约",
  // Cameroon
  "André Onana": "奥纳纳",
  "Andre Onana": "奥纳纳",
  "Vincent Aboubakar": "阿布巴卡尔",
  "Bryan Mbeumo": "姆贝乌莫",
  "Zambo Anguissa": "安古伊萨",
  // Ivory Coast
  "Sébastien Haller": "哈勒",
  "Sebastien Haller": "哈勒",
  "Franck Kessié": "凯西",
  "Seko Fofana": "福法纳",
  "Simon Adingra": "阿丁格拉",
  // Algeria
  "Riyad Mahrez": "马赫雷斯",
  "Ismaël Bennacer": "本纳赛尔",
  "Rayan Cherki": "切尔基",
  // Tunisia
  "Ellyes Skhiri": "斯希里",
  // Austria
  "David Alaba": "阿拉巴",
  "Marcel Sabitzer": "萨比策",
  "Konrad Laimer": "莱默尔",
  "Christoph Baumgartner": "鲍姆加特纳",
  // Switzerland
  "Granit Xhaka": "扎卡",
  "Manuel Akanji": "阿坎吉",
  "Yann Sommer": "索默",
  "Breel Embolo": "恩博洛",
  "Xherdan Shaqiri": "沙奇里",
  // Denmark
  "Rasmus Højlund": "霍伊伦",
  "Rasmus Hojlund": "霍伊伦",
  "Christian Eriksen": "埃里克森",
  "Pierre-Emile Højbjerg": "赫伊别尔",
  "Kasper Schmeichel": "舒梅切尔",
  "Andreas Christensen": "克里斯滕森",
  "Joakim Mæhle": "梅勒",
  // Sweden
  "Alexander Isak": "伊萨克",
  "Dejan Kulusevski": "库卢塞夫斯基",
  "Viktor Gyökeres": "哲凯赖什",
  "Viktor Gyokeres": "哲凯赖什",
  "Emil Forsberg": "福斯贝里",
  // Norway
  "Erling Haaland": "哈兰德",
  "Martin Ødegaard": "厄德高",
  "Martin Odegaard": "厄德高",
  "Alexander Sørloth": "索尔洛特",
  "Oscar Bobb": "博布",
  // Poland
  "Robert Lewandowski": "莱万多夫斯基",
  "Piotr Zieliński": "泽林斯基",
  "Wojciech Szczęsny": "什琴斯尼",
  "Nicola Zalewski": "扎莱夫斯基",
  "Jakub Kiwior": "基维奥尔",
  "Kacper Urbański": "乌尔班斯基",
  // Serbia
  "Aleksandar Mitrović": "米特罗维奇",
  "Dušan Vlahović": "弗拉霍维奇",
  "Dusan Vlahovic": "弗拉霍维奇",
  "Sergej Milinković-Savić": "米林科维奇",
  "Dušan Tadić": "塔迪奇",
  "Luka Jović": "约维奇",
  // Turkey
  "Hakan Çalhanoğlu": "恰尔汗奥卢",
  "Hakan Calhanoglu": "恰尔汗奥卢",
  "Arda Güler": "居莱尔",
  "Arda Guler": "居莱尔",
  "Kenan Yıldız": "伊尔迪兹",
  "Orkun Kökçü": "柯克曲",
  "Kerem Aktürkoğlu": "阿克图尔科格鲁",
  // Greece
  "Giorgos Masouras": "马苏拉斯",
  "Vangelis Pavlidis": "帕夫利季斯",
  // Czech Republic
  "Patrik Schick": "希克",
  "Tomáš Souček": "绍切克",
  "Vladimír Coufal": "曹法尔",
  "Adam Hložek": "赫洛泽克",
  // Ukraine
  "Mykhailo Mudryk": "穆德里克",
  "Oleksandr Zinchenko": "津琴科",
  "Artem Dovbyk": "多夫比克",
  "Andriy Lunin": "卢宁",
  "Viktor Tsygankov": "齐甘科夫",
  // Hungary
  "Dominik Szoboszlai": "索博斯洛伊",
  "Roland Sallai": "绍洛伊",
  "Barnabás Varga": "沃尔高",
  // Australia
  "Harry Souttar": "苏塔",
  "Mathew Ryan": "瑞安",
  "Ajdin Hrustic": "赫鲁斯蒂奇",
  // New Zealand
  "Chris Wood": "伍德",
  // Saudi Arabia
  "Salem Al-Dawsari": "达瓦萨里",
  "Salman Al-Faraj": "法拉吉",
  // Qatar
  "Akram Afif": "阿菲夫",
  "Almoez Ali": "阿里",
  // Iran
  "Mehdi Taremi": "塔雷米",
  "Sardar Azmoun": "阿兹蒙",
  "Alireza Jahanbakhsh": "贾汉巴赫什",
  // Peru
  "Gianluca Lapadula": "拉帕杜拉",
  "André Carrillo": "卡里略",
  // Chile
  "Alexis Sánchez": "桑切斯",
  "Ben Brereton Díaz": "布里尔顿",
  "Arturo Vidal": "比达尔",
  // Paraguay
  "Miguel Almirón": "阿尔米隆",
  "Julio Enciso": "恩西索",
  // Bolivia
  "Marcelo Martins": "莫雷诺",
  // Venezuela
  "Salomón Rondón": "隆东",
  "Yeferson Soteldo": "索特多",
  // Panama
  "Michael Murillo": "穆里略",
  // Costa Rica
  "Keylor Navas": "纳瓦斯",
  // UAE
  "Ali Mabkhout": "马布霍特",
  "Omar Abdulrahman": "奥马尔",
  // DR Congo
  "Chancel Mbemba": "姆本巴",
  "Meschack Elia": "埃利亚",
  "Yoane Wissa": "维萨",
  // Mali
  "Yves Bissouma": "比苏马",
  "Amadou Haidara": "海达拉",
  "El Bilal Touré": "比拉尔图雷",
  // Burkina Faso
  "Edmond Tapsoba": "塔普索巴",
  "Dango Ouattara": "瓦塔拉",
  // South Africa
  "Percy Tau": "塔乌",
  "Themba Zwane": "兹瓦内",
};

export function getChineseName(englishName: string): string {
  // Exact match
  if (NAME_MAP[englishName]) return NAME_MAP[englishName];
  // Try case-insensitive
  const lowered = englishName.toLowerCase();
  for (const [key, val] of Object.entries(NAME_MAP)) {
    if (key.toLowerCase() === lowered) return val;
  }
  return "";
}

// Returns "English Name (中文名)" or just "English Name"
export function formatPlayerName(englishName: string): string {
  const zh = getChineseName(englishName);
  return zh ? `${englishName} (${zh})` : englishName;
}
